---
minimum_pre_commit_version: 3.0.0
fail_fast: false
default_language_version:
  python: python3.12
repos:
  # General file checks and validation
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        types_or: [ python, yaml, toml, json ]
      - id: end-of-file-fixer
        types_or: [ python, yaml, toml, json ]
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: [ '--maxkb=20000' ]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer
  # Python code linting and formatting with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [ --fix ]
        types_or: [ python, pyi, jupyter ]
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
  # docformatter for docstrings
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        args: [ --in-place, --wrap-summaries=88, --wrap-descriptions=88 ]
  # Python code cleanup
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args: [ --py310-plus ]
        types_or: [ python, pyi ]
  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args:
          - "-c"
          - "pyproject.toml"
          - "-ll"
          - "--skip=B101,B403,B601"
        types: [ python ]
  # Jupyter notebook linting and formatting
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.7
    hooks:
      - id: nbqa-ruff
        args: [ --fix ]
        additional_dependencies: [ ruff==0.6.9 ]
        types: [ jupyter ]
      - id: nbqa-pyupgrade
        args: [ --py310-plus ]
        additional_dependencies: [ pyupgrade==3.17.0 ]
        types: [ jupyter ]
  # Notebook cell execution order and output validation
  - repo: https://github.com/mwouts/jupytext
    rev: v1.16.4
    hooks:
      - id: jupytext
        args: [ --sync ]
        types: [ jupyter ]
  # notebook quality checks
  - repo: https://github.com/srstevenson/nb-clean
    rev: 3.3.0
    hooks:
      - id: nb-clean
        args:
          - --remove-empty-cells
          - --preserve-cell-metadata
          - tags
          - --preserve-cell-outputs
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.7
    hooks:
      - id: nbqa-isort
        additional_dependencies: [ isort==6.0.1 ]
        types: [ jupyter ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [ "--profile", "black" ]
        types: [ python ]
